<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Zikula\Core\Doctrine\EntityAccess;
use MU\SoundModule\Traits\StandardFieldsTrait;
use MU\SoundModule\Validator\Constraints as SoundAssert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for track entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 */
abstract class AbstractTrackEntity extends EntityAccess implements Translatable
{
    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'track';
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     * @ORM\Column(length=20)
     * @Assert\NotBlank()
     * @SoundAssert\ListEntry(entityName="track", propertyName="workflowState", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $title
     */
    protected $title = '';
    
    /**
     * @Gedmo\Translatable
     * @ORM\Column(type="text", length=2000)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="2000")
     * @var text $description
     */
    protected $description = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="255")
     * @var string $author
     */
    protected $author = '';
    
    /**
     * Upload track meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $uploadTrackMeta
     */
    protected $uploadTrackMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "5M",
     *    mimeTypes = {"audio/*"}
     * )
     * @var string $uploadTrack
     */
    protected $uploadTrack = null;
    
    /**
     * Full upload track path as url.
     *
     * @Assert\Type(type="string")
     * @var string $uploadTrackUrl
     */
    protected $uploadTrackUrl = '';
    
    /**
     * Upload zip meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $uploadZipMeta
     */
    protected $uploadZipMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "102400",
     *    mimeTypes = {"image/*"}
     * )
     * @var string $uploadZip
     */
    protected $uploadZip = null;
    
    /**
     * Full upload zip path as url.
     *
     * @Assert\Type(type="string")
     * @var string $uploadZipUrl
     */
    protected $uploadZipUrl = '';
    
    
    /**
     * Used locale to override Translation listener's locale.
     * this is not a mapped field of entity metadata, just a simple property.
     *
     * @Assert\Locale()
     * @Gedmo\Locale
     * @var string $locale
     */
    protected $locale;
    
    /**
     * Bidirectional - Many track [tracks] are linked by one album [album] (OWNING SIDE).
     *
     * @ORM\ManyToOne(targetEntity="MU\SoundModule\Entity\AlbumEntity", inversedBy="track")
     * @ORM\JoinTable(name="mu_sound_album")
     * @Assert\Type(type="MU\SoundModule\Entity\AlbumEntity")
     * @var \MU\SoundModule\Entity\AlbumEntity $album
     */
    protected $album;
    
    
    /**
     * TrackEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     */
    public function __construct()
    {
    }
    
    /**
     * Returns the _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Sets the _object type.
     *
     * @param string $_objectType
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        if ($this->_objectType != $_objectType) {
            $this->_objectType = $_objectType;
        }
    }
    
    
    /**
     * Returns the id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Sets the id.
     *
     * @param integer $id
     *
     * @return void
     */
    public function setId($id)
    {
        if (intval($this->id) !== intval($id)) {
            $this->id = intval($id);
        }
    }
    
    /**
     * Returns the workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Sets the workflow state.
     *
     * @param string $workflowState
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($this->workflowState !== $workflowState) {
            $this->workflowState = isset($workflowState) ? $workflowState : '';
        }
    }
    
    /**
     * Returns the title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
    
    /**
     * Sets the title.
     *
     * @param string $title
     *
     * @return void
     */
    public function setTitle($title)
    {
        if ($this->title !== $title) {
            $this->title = isset($title) ? $title : '';
        }
    }
    
    /**
     * Returns the description.
     *
     * @return text
     */
    public function getDescription()
    {
        return $this->description;
    }
    
    /**
     * Sets the description.
     *
     * @param text $description
     *
     * @return void
     */
    public function setDescription($description)
    {
        if ($this->description !== $description) {
            $this->description = isset($description) ? $description : '';
        }
    }
    
    /**
     * Returns the author.
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }
    
    /**
     * Sets the author.
     *
     * @param string $author
     *
     * @return void
     */
    public function setAuthor($author)
    {
        if ($this->author !== $author) {
            $this->author = isset($author) ? $author : '';
        }
    }
    
    /**
     * Returns the upload track.
     *
     * @return string
     */
    public function getUploadTrack()
    {
        return $this->uploadTrack;
    }
    
    /**
     * Sets the upload track.
     *
     * @param string $uploadTrack
     *
     * @return void
     */
    public function setUploadTrack($uploadTrack)
    {
        if ($this->uploadTrack !== $uploadTrack) {
            $this->uploadTrack = $uploadTrack;
        }
    }
    
    /**
     * Returns the upload track url.
     *
     * @return string
     */
    public function getUploadTrackUrl()
    {
        return $this->uploadTrackUrl;
    }
    
    /**
     * Sets the upload track url.
     *
     * @param string $uploadTrackUrl
     *
     * @return void
     */
    public function setUploadTrackUrl($uploadTrackUrl)
    {
        if ($this->uploadTrackUrl !== $uploadTrackUrl) {
            $this->uploadTrackUrl = $uploadTrackUrl;
        }
    }
    
    /**
     * Returns the upload track meta.
     *
     * @return array
     */
    public function getUploadTrackMeta()
    {
        return $this->uploadTrackMeta;
    }
    
    /**
     * Sets the upload track meta.
     *
     * @param array $uploadTrackMeta
     *
     * @return void
     */
    public function setUploadTrackMeta($uploadTrackMeta = [])
    {
        if ($this->uploadTrackMeta !== $uploadTrackMeta) {
            $this->uploadTrackMeta = $uploadTrackMeta;
        }
    }
    
    /**
     * Returns the upload zip.
     *
     * @return string
     */
    public function getUploadZip()
    {
        return $this->uploadZip;
    }
    
    /**
     * Sets the upload zip.
     *
     * @param string $uploadZip
     *
     * @return void
     */
    public function setUploadZip($uploadZip)
    {
        if ($this->uploadZip !== $uploadZip) {
            $this->uploadZip = $uploadZip;
        }
    }
    
    /**
     * Returns the upload zip url.
     *
     * @return string
     */
    public function getUploadZipUrl()
    {
        return $this->uploadZipUrl;
    }
    
    /**
     * Sets the upload zip url.
     *
     * @param string $uploadZipUrl
     *
     * @return void
     */
    public function setUploadZipUrl($uploadZipUrl)
    {
        if ($this->uploadZipUrl !== $uploadZipUrl) {
            $this->uploadZipUrl = $uploadZipUrl;
        }
    }
    
    /**
     * Returns the upload zip meta.
     *
     * @return array
     */
    public function getUploadZipMeta()
    {
        return $this->uploadZipMeta;
    }
    
    /**
     * Sets the upload zip meta.
     *
     * @param array $uploadZipMeta
     *
     * @return void
     */
    public function setUploadZipMeta($uploadZipMeta = [])
    {
        if ($this->uploadZipMeta !== $uploadZipMeta) {
            $this->uploadZipMeta = $uploadZipMeta;
        }
    }
    
    /**
     * Returns the locale.
     *
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }
    
    /**
     * Sets the locale.
     *
     * @param string $locale
     *
     * @return void
     */
    public function setLocale($locale)
    {
        if ($this->locale != $locale) {
            $this->locale = $locale;
        }
    }
    
    
    /**
     * Returns the album.
     *
     * @return \MU\SoundModule\Entity\AlbumEntity
     */
    public function getAlbum()
    {
        return $this->album;
    }
    
    /**
     * Sets the album.
     *
     * @param \MU\SoundModule\Entity\AlbumEntity $album
     *
     * @return void
     */
    public function setAlbum($album = null)
    {
        $this->album = $album;
    }
    
    
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return array The resulting arguments list
     */
    public function createUrlArgs()
    {
        return [
            'id' => $this->getId()
        ];
    }
    
    /**
     * Returns the primary key.
     *
     * @return integer The identifier
     */
    public function getKey()
    {
        return $this->getId();
    }
    
    /**
     * Determines whether this entity supports hook subscribers or not.
     *
     * @return boolean
     */
    public function supportsHookSubscribers()
    {
        return true;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'musoundmodule.ui_hooks.tracks';
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     * 
     * @param array $objects The objects are added to this array. Default: []
     * 
     * @return array of entity objects
     */
    public function getRelatedObjectsToPersist(&$objects = []) 
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     *
     * @return string The output string for this entity
     */
    public function __toString()
    {
        return 'Track ' . $this->getKey() . ': ' . $this->getTitle();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!$this->id) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifier
        $this->setId(0);
    
        // reset workflow
        $this->setWorkflowState('initial');
    
        // reset upload fields
        $this->setUploadTrack(null);
        $this->setUploadTrackMeta([]);
        $this->setUploadTrackUrl('');
        $this->setUploadZip(null);
        $this->setUploadZipMeta([]);
        $this->setUploadZipUrl('');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    
    }
}
