<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Installer implementation class.
 */
class MUSound_Installer extends MUSound_Base_AbstractInstaller
{
	/**
	 * Upgrade the MUSound application from an older version.
	 *
	 * If the upgrade fails at some point, it returns the last upgraded version.
	 *
	 * @param integer $oldVersion Version to upgrade from.
	 *
	 * @return boolean True on success, false otherwise.
	 */
	public function upgrade($oldVersion)
	{
		 // Upgrade dependent on old version number
		 switch ($oldVersion) {
		 	
		 case '1.0.0':
			$this->setVar('supportedModuls', '');
			$this->setVar('useStandard', false);
			$this->setVar('orderOfCollections', '');
			$this->setVar('orderOfAlbums', '');
			
		 // update the database schema
		 try {
		 DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
		 } catch (\Exception $e) {
		 if (System::isDevelopmentMode()) {
		 return LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
		 }
		 return LogUtil::registerError($this->__f('An error was encountered while updating tables for the %s extension.', array($this->getName())));
		 }
		 }
	
		// update successful
		return true;
	}
}
