<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Upload handler implementation class.
 */
class MUSound_UploadHandler extends MUSound_Base_UploadHandler

{
    /**
     * Constructor initialising the supported object types.
     */
    public function __construct()
    {
        parent::__construct();
        $this->allowedFileSizes['album'] = ModUtil::getVar('VerySimpleDownload', 'maxSizeCover', 102400);
        $this->allowedFileSizes = array('album' => array('uploadCover' => ModUtil::getVar('MUSound', 'maxSizeCover', 102400)), 'track' => array('uploadTrack' => ModUtil::getVar('MUSound', 'maxSizeTrack', 102400), 'uploadZip' => 1024000));

    }
}