<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Form\Type;

use MU\SoundModule\Form\Type\Base\AbstractAlbumType;

/**
 * Album editing form type implementation class.
 */
class AlbumType extends AbstractAlbumType
{
    // feel free to extend the album editing form type class here
}
