<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Event;

use MU\SoundModule\Event\Base\AbstractFilterAlbumEvent;

/**
 * Event implementation class for filtering album processing.
 */
class FilterAlbumEvent extends AbstractFilterAlbumEvent
{
    // feel free to extend the event class here
}
