<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Paginator switch implementation class for making 1.3.x modules work with 1.4.
 */
class MUSound_Paginator_Paginator extends MUSound_Paginator_Base_AbstractPaginator
{
    // extend the paginator class here if desired
}
