<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Form\Type\Finder;

use MU\SoundModule\Form\Type\Finder\Base\AbstractTrackFinderType;

/**
 * Track finder form type implementation class.
 */
class TrackFinderType extends AbstractTrackFinderType
{
    // feel free to extend the base form type class here
}
