<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class MUSound_TaggedObjectMeta_MUSound extends MUSound_TaggedObjectMeta_Base_MUSound
{
    // feel free to extend the tag support here
}
