<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUSound_track_edit() function.
 * It aims on the track object type.
 */
class MUSound_Form_Handler_Track_Edit extends MUSound_Form_Handler_Track_Base_AbstractEdit
{
    // feel free to extend the base handler class here
}
