<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * MUSound album needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUSound_needleapi_album_baseInfo()
{
    $info = array(
        // module name
        'module'  => 'MUSound',
        // possible needles
        'info'    => 'MUSOUND{ALBUMS|ALBUM-albumId}',
        // whether a reverse lookup is possible, needs MUSound_needleapi_album_inspect() function
        'inspect' => false
    );

    return $info;
}
