<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Form\Handler\Album;

use MU\SoundModule\Form\Handler\Album\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the mUSoundModule_album_edit() function.
 * It aims on the album object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
