<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule;

use MU\SoundModule\Base\AbstractSoundModuleInstaller;

/**
 * Installer implementation class.
 */
class SoundModuleInstaller extends AbstractSoundModuleInstaller
{
    // feel free to extend the installer here
}
