<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Relation selector plugin implementation class.
 */
class MUSound_Form_Plugin_RelationSelectorAutoComplete extends MUSound_Form_Plugin_Base_AbstractRelationSelectorAutoComplete
{
    // feel free to add your customisation here
}
