<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\HookSubscriber;

use MU\SoundModule\HookSubscriber\Base\AbstractAlbumFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class AlbumFormAwareHookSubscriber extends AbstractAlbumFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
