<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license 
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUSound_user_edit() function.
 * It aims on the album object type.
 */
class MUSound_Form_Handler_User_Album_Edit extends MUSound_Form_Handler_User_Album_Base_Edit
{
    // feel free to extend the base handler class here
}
