<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\SoundModule\Entity\TrackEntity;

/**
 * Event base class for filtering track processing.
 */
class AbstractFilterTrackEvent extends Event
{
    /**
     * @var TrackEntity Reference to treated entity instance.
     */
    protected $track;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterTrackEvent constructor.
     *
     * @param TrackEntity $track Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(TrackEntity $track, $entityChangeSet = [])
    {
        $this->track = $track;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return TrackEntity
     */
    public function getTrack()
    {
        return $this->track;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
