<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing album categories.
 *
 * This is the base category class for album entities.
 */
abstract class MUSound_Entity_Base_AbstractAlbumCategory extends Zikula_Doctrine2_Entity_EntityCategory
{
    /**
     * @ORM\ManyToOne(targetEntity="MUSound_Entity_Album", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var MUSound_Entity_Album
     */
    protected $entity;
    
    /**
     * Get reference to owning entity.
     *
     * @return MUSound_Entity_Album
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param MUSound_Entity_Album $entity
     */
    public function setEntity(/*MUSound_Entity_Album */$entity)
    {
        $this->entity = $entity;
    }
}
