<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

include_once 'Needles/Base/Abstractalbum_info.php';

/**
 * MUSound album needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUSound_needleapi_album_info()
{
    return MUSound_needleapi_album_baseInfo();
}
