<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

include_once 'Needles/Base/Abstracttrack_info.php';

/**
 * MUSound track needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUSound_needleapi_track_info()
{
    return MUSound_needleapi_track_baseInfo();
}
