<?php
/**
 * MUSound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSound
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Configuration handler implementation class.
 */
class MUSound_Form_Handler_Admin_Config extends MUSound_Form_Handler_Admin_Base_AbstractConfig
{
    // feel free to extend the base handler class here
}
