modules/MUSound/templates/album/main.tpl: config/templates/MUSound/album/main.tpl
modules/MUSound/templates/album/view.tpl: config/templates/MUSound/album/view.tpl
modules/MUSound/templates/album/viewQuickNav.tpl: config/templates/MUSound/album/viewQuickNav.tpl
modules/MUSound/templates/album/view.rss.tpl: config/templates/MUSound/album/view.rss.tpl
modules/MUSound/templates/album/display.tpl: config/templates/MUSound/album/display.tpl
modules/MUSound/templates/album/delete.tpl: config/templates/MUSound/album/delete.tpl
modules/MUSound/templates/album/includeDisplayItemListOne.tpl: config/templates/MUSound/album/includeDisplayItemListOne.tpl
modules/MUSound/templates/album/includeDisplayItemListMany.tpl: config/templates/MUSound/album/includeDisplayItemListMany.tpl
modules/MUSound/templates/track/main.tpl: config/templates/MUSound/track/main.tpl
modules/MUSound/templates/track/view.tpl: config/templates/MUSound/track/view.tpl
modules/MUSound/templates/track/viewQuickNav.tpl: config/templates/MUSound/track/viewQuickNav.tpl
modules/MUSound/templates/track/view.rss.tpl: config/templates/MUSound/track/view.rss.tpl
modules/MUSound/templates/track/display.tpl: config/templates/MUSound/track/display.tpl
modules/MUSound/templates/track/delete.tpl: config/templates/MUSound/track/delete.tpl
modules/MUSound/templates/track/includeDisplayItemListOne.tpl: config/templates/MUSound/track/includeDisplayItemListOne.tpl
modules/MUSound/templates/track/includeDisplayItemListMany.tpl: config/templates/MUSound/track/includeDisplayItemListMany.tpl
modules/MUSound/templates/collection/main.tpl: config/templates/MUSound/collection/main.tpl
modules/MUSound/templates/collection/view.tpl: config/templates/MUSound/collection/view.tpl
modules/MUSound/templates/collection/viewQuickNav.tpl: config/templates/MUSound/collection/viewQuickNav.tpl
modules/MUSound/templates/collection/view.rss.tpl: config/templates/MUSound/collection/view.rss.tpl
modules/MUSound/templates/collection/display.tpl: config/templates/MUSound/collection/display.tpl
modules/MUSound/templates/collection/delete.tpl: config/templates/MUSound/collection/delete.tpl
modules/MUSound/templates/admin/header.tpl: config/templates/MUSound/admin/header.tpl
modules/MUSound/templates/admin/footer.tpl: config/templates/MUSound/admin/footer.tpl
modules/MUSound/templates/user/header.tpl: config/templates/MUSound/user/header.tpl
modules/MUSound/templates/user/footer.tpl: config/templates/MUSound/user/footer.tpl
modules/MUSound/templates/admin/inlineRedirectHandler.tpl: config/templates/MUSound/admin/inlineRedirectHandler.tpl
modules/MUSound/templates/user/inlineRedirectHandler.tpl: config/templates/MUSound/user/inlineRedirectHandler.tpl
modules/MUSound/templates/album/edit.tpl: config/templates/MUSound/album/edit.tpl
modules/MUSound/templates/album/inlineRedirectHandler.tpl: config/templates/MUSound/album/inlineRedirectHandler.tpl
modules/MUSound/templates/track/edit.tpl: config/templates/MUSound/track/edit.tpl
modules/MUSound/templates/track/inlineRedirectHandler.tpl: config/templates/MUSound/track/inlineRedirectHandler.tpl
modules/MUSound/templates/collection/edit.tpl: config/templates/MUSound/collection/edit.tpl
modules/MUSound/templates/collection/inlineRedirectHandler.tpl: config/templates/MUSound/collection/inlineRedirectHandler.tpl
modules/MUSound/templates/helper/includeCategoriesDisplay.tpl: config/templates/MUSound/helper/includeCategoriesDisplay.tpl
modules/MUSound/templates/helper/includeCategoriesEdit.tpl: config/templates/MUSound/helper/includeCategoriesEdit.tpl
modules/MUSound/templates/helper/includeStandardFieldsDisplay.tpl: config/templates/MUSound/helper/includeStandardFieldsDisplay.tpl
modules/MUSound/templates/helper/includeStandardFieldsEdit.tpl: config/templates/MUSound/helper/includeStandardFieldsEdit.tpl
modules/MUSound/templates/admin/config.tpl: config/templates/MUSound/admin/config.tpl
modules/MUSound/templates/email/notifyAlbumCreator.tpl: config/templates/MUSound/email/notifyAlbumCreator.tpl
modules/MUSound/templates/email/notifyAlbumModerator.tpl: config/templates/MUSound/email/notifyAlbumModerator.tpl
modules/MUSound/templates/includePdfHeader.tpl: config/templates/MUSound/includePdfHeader.tpl
