<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Entity;

use MU\SoundModule\Entity\Base\AbstractAlbumCategoryEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing album categories.
 *
 * This is the concrete category class for album entities.
 * @ORM\Entity(repositoryClass="\MU\SoundModule\Entity\Repository\AlbumCategoryRepository")
 * @ORM\Table(name="mu_sound_album_category",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
 *     }
 * )
 */
class AlbumCategoryEntity extends BaseEntity
{
    // feel free to add your own methods here
}
