<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Entity;

use MU\SoundModule\Entity\Base\AbstractTrackTranslationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing track translations.
 *
 * This is the concrete translation class for track entities.
 *
 * @ORM\Entity(repositoryClass="MU\SoundModule\Entity\Repository\TrackTranslationRepository")
 * @ORM\Table(name="mu_sound_track_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class TrackTranslationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
