<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Entity\Factory\Base;

use MU\SoundModule\Entity\AlbumEntity;
use MU\SoundModule\Entity\TrackEntity;
use MU\SoundModule\Entity\CollectionEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given album instance.
     *
     * @param AlbumEntity $entity The newly created entity instance
     *
     * @return AlbumEntity The updated entity instance
     */
    public function initAlbum(AlbumEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given track instance.
     *
     * @param TrackEntity $entity The newly created entity instance
     *
     * @return TrackEntity The updated entity instance
     */
    public function initTrack(TrackEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given collection instance.
     *
     * @param CollectionEntity $entity The newly created entity instance
     *
     * @return CollectionEntity The updated entity instance
     */
    public function initCollection(CollectionEntity $entity)
    {

        return $entity;
    }

}
