services:
    # Entity factory
    mu_sound_module.entity_factory:
        class: MU\SoundModule\Entity\Factory\EntityFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@mu_sound_module.entity_initialiser"
            - "@mu_sound_module.collection_filter_helper"
            - "@mu_sound_module.feature_activation_helper"
    
    # Entity initialiser
    mu_sound_module.entity_initialiser:
        class: MU\SoundModule\Entity\Factory\EntityInitialiser
