services:
    # Custom validators
    mu_sound_module.validator.list_entry.validator:
        class: MU\SoundModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_sound_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_sound_module.validator.list_entry.validator }
