<?php
/**
 * Sound.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\SoundModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractSoundEvents
{
    /**
     * The musoundmodule.album_post_load event is thrown when albums
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterAlbumEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const ALBUM_POST_LOAD = 'musoundmodule.album_post_load';
    
    /**
     * The musoundmodule.album_pre_persist event is thrown before a new album
     * is created in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterAlbumEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const ALBUM_PRE_PERSIST = 'musoundmodule.album_pre_persist';
    
    /**
     * The musoundmodule.album_post_persist event is thrown after a new album
     * has been created in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterAlbumEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const ALBUM_POST_PERSIST = 'musoundmodule.album_post_persist';
    
    /**
     * The musoundmodule.album_pre_remove event is thrown before an existing album
     * is removed from the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterAlbumEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const ALBUM_PRE_REMOVE = 'musoundmodule.album_pre_remove';
    
    /**
     * The musoundmodule.album_post_remove event is thrown after an existing album
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterAlbumEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const ALBUM_POST_REMOVE = 'musoundmodule.album_post_remove';
    
    /**
     * The musoundmodule.album_pre_update event is thrown before an existing album
     * is updated in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterAlbumEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const ALBUM_PRE_UPDATE = 'musoundmodule.album_pre_update';
    
    /**
     * The musoundmodule.album_post_update event is thrown after an existing new album
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterAlbumEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const ALBUM_POST_UPDATE = 'musoundmodule.album_post_update';
    
    /**
     * The musoundmodule.track_post_load event is thrown when tracks
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterTrackEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const TRACK_POST_LOAD = 'musoundmodule.track_post_load';
    
    /**
     * The musoundmodule.track_pre_persist event is thrown before a new track
     * is created in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterTrackEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const TRACK_PRE_PERSIST = 'musoundmodule.track_pre_persist';
    
    /**
     * The musoundmodule.track_post_persist event is thrown after a new track
     * has been created in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterTrackEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const TRACK_POST_PERSIST = 'musoundmodule.track_post_persist';
    
    /**
     * The musoundmodule.track_pre_remove event is thrown before an existing track
     * is removed from the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterTrackEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const TRACK_PRE_REMOVE = 'musoundmodule.track_pre_remove';
    
    /**
     * The musoundmodule.track_post_remove event is thrown after an existing track
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterTrackEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const TRACK_POST_REMOVE = 'musoundmodule.track_post_remove';
    
    /**
     * The musoundmodule.track_pre_update event is thrown before an existing track
     * is updated in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterTrackEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const TRACK_PRE_UPDATE = 'musoundmodule.track_pre_update';
    
    /**
     * The musoundmodule.track_post_update event is thrown after an existing new track
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterTrackEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const TRACK_POST_UPDATE = 'musoundmodule.track_post_update';
    
    /**
     * The musoundmodule.collection_post_load event is thrown when collections
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterCollectionEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const COLLECTION_POST_LOAD = 'musoundmodule.collection_post_load';
    
    /**
     * The musoundmodule.collection_pre_persist event is thrown before a new collection
     * is created in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterCollectionEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const COLLECTION_PRE_PERSIST = 'musoundmodule.collection_pre_persist';
    
    /**
     * The musoundmodule.collection_post_persist event is thrown after a new collection
     * has been created in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterCollectionEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const COLLECTION_POST_PERSIST = 'musoundmodule.collection_post_persist';
    
    /**
     * The musoundmodule.collection_pre_remove event is thrown before an existing collection
     * is removed from the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterCollectionEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const COLLECTION_PRE_REMOVE = 'musoundmodule.collection_pre_remove';
    
    /**
     * The musoundmodule.collection_post_remove event is thrown after an existing collection
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterCollectionEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const COLLECTION_POST_REMOVE = 'musoundmodule.collection_post_remove';
    
    /**
     * The musoundmodule.collection_pre_update event is thrown before an existing collection
     * is updated in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterCollectionEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const COLLECTION_PRE_UPDATE = 'musoundmodule.collection_pre_update';
    
    /**
     * The musoundmodule.collection_post_update event is thrown after an existing new collection
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\SoundModule\Event\FilterCollectionEvent instance.
     *
     * @see MU\SoundModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const COLLECTION_POST_UPDATE = 'musoundmodule.collection_post_update';
    
}
